[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
amm = "5GwvY98CgoPByjWEz2ZL6yK2J7oZvKNySrMSSR3E4RU4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/jogeshwar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
