[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
staking = "FhqzRxobtLDbbdaJXFfx6Tei2iosd9T2UeXvo96FTZbN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/jogeshwar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
